### ISSUE TITLE
Build instructions dont seem to work

### ISSUE THREAD

**Issue by MichaelAquilina** [elementary/Vala-Lint#25]
After following the README, I cant seem to use vala-lint or even find the binary in my system. Nothing seems to have failed along the way.

the output of the last `make install` doesn show any `vala-lint` file in its output
```
$ sudo make install
[100%] Built target vala-lint-1.0
[100%] Built target i18n
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/lib64/libvala-lint-1.0.so.0.1.0
-- Up-to-date: /usr/lib64/libvala-lint-1.0.so.0
-- Up-to-date: /usr/lib64/libvala-lint-1.0.so
-- Up-to-date: /usr/lib64/pkgconfig/vala-lint-1.0.pc
-- Up-to-date: /usr/share/vala/vapi/vala-lint-1.0.vapi
-- Up-to-date: /usr/share/vala/vapi/vala-lint-1.0.deps
-- Up-to-date: /usr/include/vala-lint-1.0/vala-lint.h
```

**Comment by Philip-Scott** [comment]
I'm guessing you only looked at the top of the instructions, and ran cmake with `-DLIBRARY_ONLY=ON ` :wink: 

Follow the instructions bellow https://github.com/elementary/Vala-Lint#command-line-tool :) 


Please be aware though that this project is currently abandoned, and i don't think much work was done with it.... but if you want to help us with it it would be appreciated :)
