### ISSUE TITLE
After installing to /usr/local the app doesn't work

### ISSUE THREAD

**Issue by cjfloss** [elementary/vala-lint#42]
I ran
```
meson build
cd build
ninja
sudo ninja install
```

and then 

> io.elementary.vala-lint -d ~/Projects/envelope/src

I get the error

> io.elementary.vala-lint: error while loading shared libraries: libvala-linter-1.0.so: cannot open shared object file: No such file or directory

but if I configure it with `meson build --prefix=/usr` works fine

**Comment by pantor** [comment]
In the Readme, we actually run `meson build --prefix=/usr` to build vala-lint. I'm not sure, maybe I'm missing something?
