### ISSUE TITLE
Package it!

### ISSUE THREAD

**Issue by cassidyjames** [elementary/vala-lint#46]
We should package this and ship it in our repo, so we can make elementary-sdk depend on it and use it in CI.

cc @btkostner

**Comment by tintou** [comment]
Don't hesitate to do:
```io.elementary.vala-lint```

**Comment by danrabbit** [comment]
It’s already done :) `io.elementary.vala-lint`

**Comment by cassidyjames** [comment]
@btkostner you make me a fool

**Comment by btkostner** [comment]
_delete the evidence_

**Comment by rythmkraze** [comment]
Has this been packaged yet? I can't find it in the repo.

**Comment by btkostner** [comment]
It has, see #68
