### ISSUE TITLE
Has this been packaged into a repo?

### ISSUE THREAD

**Issue by rythmkraze** [elementary/vala-lint#68]
I am unable to find this in the repo.

```
$ sudo apt search io.elementary.vala-lint
$ sudo apt search vala-lint
```

**Comment by jonafato** [comment]
Per [this comment](https://github.com/elementary/vala-lint/issues/44#issuecomment-366322722), `io.elementary.vala-lint` can be found in the [elementary Daily PPA](https://launchpad.net/~elementary-os/+archive/ubuntu/daily). Note that this is only available for Bionic and Disco, not older releases.

**Comment by rythmkraze** [comment]
Thanks, @jonafato . Will work with that.

Any reason this is not part of the main/default repo?

**Comment by codygarver** [comment]
See pull request #69

**Comment by rythmkraze** [comment]
Got it. Thanks @codygarver
