### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by cstayyab** [elementary/vala-lint#72]
I am trying to install it using `sudo apt install io.elementary.vala-lint` and following error occurs:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package io.elementary.vala-lint is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'io.elementary.vala-lint' has no installation candidate
```
I am using Elementary Juno. I have `elementary-sdk` installed.

**Comment by codygarver** [comment]
Since vala-lint is intended to be always up-to-date, the recommended usage is the docker image. See the README section for more info https://github.com/elementary/vala-lint#docker-and-continuous-integration
