### ISSUE TITLE
Don't warn on NOTE comments

### ISSUE THREAD

**Issue by cassidyjames** [elementary/vala-lint#79]
PR #75 introduced warnings for `FIXME`, `TODO`, and `NOTE` comments. The former two were what were requested in #48, as both `FIXME` and `TODO` imply a non-ideal or unfinished state that a developer might want to address before committing.

However, `NOTE` should **not** elicit a warning as it's perfectly fine to add clarifying comments. We don't want to discourage that with warnings.

**Comment by jeremypw** [comment]
It could be argued that a clarifying comment does not need to be marked "NOTE" (all comments are for the purpose of clarification of some kind).  This should only be used for particularly important comments.
