### ISSUE TITLE
Create Code plugin for Vala-Lint

### ISSUE THREAD

**Issue by marioguerriero** [elementary/vala-lint#9]
I think it would be interesting to have a Vala linter inside Scratch

**Comment by MarcusWichelmann** [comment]
Good idea, should be possible using the current structure of the library. We only need to package it to make it easily available in elementary OS.

**Comment by pantor** [comment]
As this issue should be in the code repository, I've opened issue [#697](https://github.com/elementary/code/issues/697) there. I'll close this here.
